export 'package:bigdeals2/tabs/home_tab/widget/product_item.dart';
export 'package:bigdeals2/tabs/home_tab/widget/menu_item.dart';
export 'package:flutter/material.dart';
export 'package:bigdeals2/tabs/home_tab/widget/list_item.dart';
export 'package:bigdeals2/tabs/home_tab/widget/list_category.dart';
export 'package:bigdeals2/tabs/home_tab/widget/products_of_categories.dart';
export 'package:bigdeals2/tabs/home_tab/widget/product_details.dart';
export 'package:bigdeals2/tabs/home_tab/widget/view_more.dart';
export 'package:bigdeals2/tabs/home_tab/widget/slide_itemm.dart';